language: node_js
sudo: false
node_js:
- '6'

addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
  - ./node_modules/.bin/karma start --single-run --browsers Firefox --reporters mocha
